spring:
  liquibase:
    change-log: classpath:db/changelog/liquibase_changelog.xml
    enabled: true
  profiles:
    active: development
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oro
    username: postgres
    password: postgres

server:
  servlet:
    context-path: /api
  port: 8080
  tomcat:
    accesslog:
      enabled: true
    directory: logs
    file-date-format: yyyy-mm-dd
    prefix: access_log
    suffix: .log

